"use client";

import { useEffect, useState } from "react";
import { adminMutation } from "./admin-api";

type Route = { method: "CARD" | "SBP"; provider: "YOOKASSA" | "TBANK"; isActive: boolean };
type Zone = { id: string; name: string; city: string; feeKopecks: number; freeThresholdKopecks: number | null; minOrderKopecks: number | null; isActive: boolean; version: number };
type Hours = { weekday: number; opensAt: string | null; closesAt: string | null; isClosed: boolean; slotLength: number; capacity: number | null };
type Settings = { store: { version: number; leadTimeMinutes: number; minimumOrderKopecks: number | null; legalBasis: "CONTRACT" | "CONSENT"; taxSystemCode: string | null; commerceMode: "MENU_ONLY" | "ORDERS" | "ONLINE_PAYMENT"; demoOrdersEnabled: boolean }; zones: Zone[]; hours: Hours[]; routing: Route[] };
const days = ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"];
const rubles = (value: number | null) => value === null ? "" : String(value / 100);
const kopecks = (value: FormDataEntryValue | null) => value === null || value === "" ? null : Math.round(Number(value) * 100);

export function AdminSettings() {
  const [data, setData] = useState<Settings | null>(null);
  const [message, setMessage] = useState("");
  const load = () => fetch("/api/admin/settings", { cache: "no-store" }).then(async (response) => setData(await response.json() as Settings));
  useEffect(() => { void load(); }, []);
  if (!data) return <p>Загрузка…</p>;
  async function mutate(payload: Record<string, unknown>, success: string) { try { await adminMutation("/api/admin/settings", "PATCH", payload); setMessage(success); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Ошибка"); } }
  async function saveStore(form: HTMLFormElement) { const f = new FormData(form); await mutate({ operation: "store", version: data!.store.version, leadTimeMinutes: Number(f.get("lead")), minimumOrderKopecks: kopecks(f.get("minimum")), legalBasis: f.get("basis"), taxSystemCode: f.get("tax") || null, commerceMode: f.get("commerceMode"), demoOrdersEnabled: f.get("demoOrdersEnabled") === "on" }, "Режим и настройки сохранены"); }
  async function saveZone(form: HTMLFormElement, zone?: Zone) { const f = new FormData(form); await mutate({ operation: "zone", ...(zone ? { id: zone.id, version: zone.version } : {}), name: f.get("name"), city: f.get("city"), feeKopecks: kopecks(f.get("fee")) ?? 0, freeThresholdKopecks: kopecks(f.get("free")), minOrderKopecks: kopecks(f.get("minimum")), isActive: f.get("active") === "on" }, zone ? "Зона сохранена" : "Зона добавлена"); if (!zone) form.reset(); }
  async function saveHours(form: HTMLFormElement, weekday: number) { const f = new FormData(form); const closed = f.get("closed") === "on"; await mutate({ operation: "hours", weekday, opensAt: closed ? null : f.get("opensAt"), closesAt: closed ? null : f.get("closesAt"), isClosed: closed, slotLength: Number(f.get("slotLength")), capacity: f.get("capacity") ? Number(f.get("capacity")) : null }, `${days[weekday]}: часы сохранены`); }
  async function routing(form: HTMLFormElement) { const f = new FormData(form); try { const reauth = await adminMutation("/api/admin/reauth", "POST", { password: f.get("password"), totpCode: f.get("totp") }) as { nonce: string }; await adminMutation("/api/admin/payment-routing", "POST", { nonce: reauth.nonce, routes: [{ method: "CARD", provider: f.get("card"), isActive: true }, { method: "SBP", provider: f.get("sbp"), isActive: true }] }); setMessage("Маршрутизация оплаты сохранена"); form.reset(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Ошибка"); } }
  const current = (method: "CARD" | "SBP") => data.routing.find((route) => route.method === method)?.provider ?? "YOOKASSA";

  return <section style={{ padding: "30px 0" }}><h1>Настройки</h1>{message ? <p role="status">{message}</p> : null}
    <form className="admin-card" onSubmit={(e) => { e.preventDefault(); void saveStore(e.currentTarget); }}><h2>Режим сайта</h2><div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))" }}><label>Продажи<select className="admin-field" name="commerceMode" defaultValue={data.store.commerceMode}><option value="MENU_ONLY">Только меню</option><option value="ORDERS">Заказы без онлайн-оплаты</option><option value="ONLINE_PAYMENT">Заказы с онлайн-оплатой</option></select></label><label><input name="demoOrdersEnabled" type="checkbox" defaultChecked={data.store.demoOrdersEnabled} /> Разрешить тестовые заказы</label><label>Подготовка, минут<input className="admin-field" name="lead" type="number" min="1" max="240" defaultValue={data.store.leadTimeMinutes} /></label><label>Минимальный заказ, ₽<input className="admin-field" name="minimum" type="number" min="0" step="0.01" defaultValue={rubles(data.store.minimumOrderKopecks)} /></label><label>Основание обработки<select className="admin-field" name="basis" defaultValue={data.store.legalBasis}><option value="CONTRACT">Исполнение договора</option><option value="CONSENT">Согласие</option></select></label><label>СНО<input className="admin-field" name="tax" defaultValue={data.store.taxSystemCode ?? ""} /></label><button className="admin-button">Сохранить v{data.store.version}</button></div></form>
    <h2>Зоны доставки</h2>{data.zones.map((zone) => <form className="admin-card" key={zone.id} onSubmit={(e) => { e.preventDefault(); void saveZone(e.currentTarget, zone); }}><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))" }}><label>Название<input className="admin-field" name="name" defaultValue={zone.name} required /></label><label>Город<input className="admin-field" name="city" defaultValue={zone.city} required /></label><label>Доставка, ₽<input className="admin-field" name="fee" type="number" min="0" step="0.01" defaultValue={rubles(zone.feeKopecks)} required /></label><label>Бесплатно от, ₽<input className="admin-field" name="free" type="number" min="0" step="0.01" defaultValue={rubles(zone.freeThresholdKopecks)} /></label><label>Минимум, ₽<input className="admin-field" name="minimum" type="number" min="0" step="0.01" defaultValue={rubles(zone.minOrderKopecks)} /></label><label><input name="active" type="checkbox" defaultChecked={zone.isActive} /> Активна</label><button className="admin-button">Сохранить v{zone.version}</button></div></form>)}
    <form className="admin-card" onSubmit={(e) => { e.preventDefault(); void saveZone(e.currentTarget); }}><h3>Добавить зону</h3><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(145px,1fr))" }}><input className="admin-field" name="name" placeholder="Название" required /><input className="admin-field" name="city" placeholder="Город" required /><input className="admin-field" name="fee" type="number" min="0" step="0.01" placeholder="Стоимость, ₽" required /><input className="admin-field" name="free" type="number" min="0" step="0.01" placeholder="Бесплатно от, ₽" /><input className="admin-field" name="minimum" type="number" min="0" step="0.01" placeholder="Минимум, ₽" /><label><input name="active" type="checkbox" defaultChecked /> Активна</label><button className="admin-button">Добавить</button></div></form>
    <h2>Часы работы</h2><div style={{ display: "grid", gap: 10 }}>{days.map((day, weekday) => { const value = data.hours.find((item) => item.weekday === weekday); return <form className="admin-card" key={day} onSubmit={(e) => { e.preventDefault(); void saveHours(e.currentTarget, weekday); }}><strong>{day}</strong><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(130px,1fr))", marginTop: 8 }}><label>Открытие<input className="admin-field" name="opensAt" type="time" defaultValue={value?.opensAt ?? "10:00"} /></label><label>Закрытие<input className="admin-field" name="closesAt" type="time" defaultValue={value?.closesAt ?? "22:00"} /></label><label>Шаг, минут<input className="admin-field" name="slotLength" type="number" min="5" max="240" defaultValue={value?.slotLength ?? 30} /></label><label>Заказов на слот<input className="admin-field" name="capacity" type="number" min="1" defaultValue={value?.capacity ?? ""} /></label><label><input name="closed" type="checkbox" defaultChecked={value?.isClosed} /> Выходной</label><button className="admin-button">Сохранить</button></div></form>; })}</div>
    <form className="admin-card" onSubmit={(e) => { e.preventDefault(); void routing(e.currentTarget); }}><h2>Онлайн-оплата · повторная аутентификация</h2><div style={{ display: "grid", gap: 12, gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))" }}><label>Карта<select className="admin-field" name="card" defaultValue={current("CARD")}><option value="YOOKASSA">ЮKassa</option><option value="TBANK">Т-Банк</option></select></label><label>СБП<select className="admin-field" name="sbp" defaultValue={current("SBP")}><option value="YOOKASSA">ЮKassa</option><option value="TBANK">Т-Банк</option></select></label><label>Пароль<input className="admin-field" name="password" type="password" required /></label><label>Код MFA<input className="admin-field" name="totp" inputMode="numeric" pattern="\d{6}" required /></label><button className="admin-button">Сохранить оплату</button></div></form>
  </section>;
}
