"use client";
import { useEffect, useState } from "react";
import { adminMutation } from "./admin-api";

type User = { id: string; emailNormalized: string; role: string; isActive: boolean; mfaEnrolledAt: string | null; permissions: Array<{ code: string }> };
type Handoff = { enrollmentUri: string; recoveryCodes: string[] };
export function AdminUsers() {
  const [users, setUsers] = useState<User[]>([]); const [message, setMessage] = useState(""); const [handoff, setHandoff] = useState<Handoff | null>(null);
  const load = () => fetch("/api/admin/users", { cache: "no-store" }).then(async (response) => setUsers(await response.json() as User[])); useEffect(() => { void load(); }, []);
  async function create(form: HTMLFormElement) { const data = new FormData(form); try { const result = await adminMutation("/api/admin/users", "POST", { email: data.get("email"), password: data.get("password"), role: data.get("role"), refundPermission: data.get("refund") === "on" }) as Partial<Handoff>; setHandoff(result.enrollmentUri && result.recoveryCodes ? result as Handoff : null); setMessage("Пользователь создан. Передайте данные входа отдельно."); form.reset(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Ошибка"); } }
  async function access(user: User) { try { await adminMutation(`/api/admin/users/${user.id}`, "PATCH", { operation: "active", isActive: !user.isActive }); setMessage(user.isActive ? "Доступ отозван, активные сессии закрыты" : "Доступ восстановлен"); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Ошибка"); } }
  async function resetPassword(user: User, form: HTMLFormElement) { const data = new FormData(form); try { await adminMutation(`/api/admin/users/${user.id}`, "PATCH", { operation: "password", password: data.get("password") }); setMessage("Пароль изменён, активные сессии закрыты"); form.reset(); } catch (error) { setMessage(error instanceof Error ? error.message : "Ошибка"); } }
  return <section style={{ padding: "30px 0" }}><h1>Пользователи</h1>{message ? <p role="status">{message}</p> : null}
    {handoff ? <div className="admin-card" style={{ border: "2px solid #ff6b00" }}><h2>Сохраните один раз и передайте клиенту</h2><p style={{ wordBreak: "break-all" }}><b>MFA URI:</b> {handoff.enrollmentUri}</p><p><b>Коды восстановления:</b><br />{handoff.recoveryCodes.join(" · ")}</p><button className="admin-button" onClick={() => setHandoff(null)}>Я сохранил</button></div> : null}
    <form className="admin-card" onSubmit={(event) => { event.preventDefault(); void create(event.currentTarget); }}><h2>Новый пользователь</h2><div style={{ display: "grid", gap: 10, gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))" }}><input className="admin-field" name="email" type="email" placeholder="Email" required /><input className="admin-field" name="password" type="password" minLength={14} placeholder="Временный пароль ≥ 14 символов" required /><label>Роль<select className="admin-field" name="role" defaultValue="MANAGER"><option value="MANAGER">Менеджер</option><option value="ADMIN">Администратор клиента</option></select></label><label><input type="checkbox" name="refund" /> Разрешить возвраты</label><button className="admin-button">Создать</button></div></form>
    <div style={{ marginTop: 20, display: "grid", gap: 8 }}>{users.map((user) => <div className="admin-card" key={user.id}><b>{user.emailNormalized}</b> · {user.role} · {user.isActive ? "активен" : "отключён"} · {user.mfaEnrolledAt ? "MFA подтверждена" : user.role === "ADMIN" ? "ожидает первого входа с MFA" : "MFA не требуется"}<div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}><button className="admin-button" type="button" onClick={() => void access(user)}>{user.isActive ? "Отозвать доступ" : "Вернуть доступ"}</button><form onSubmit={(event) => { event.preventDefault(); void resetPassword(user, event.currentTarget); }} style={{ display: "flex", gap: 8 }}><input className="admin-field" name="password" type="password" minLength={14} placeholder="Новый пароль" required /><button className="admin-button">Сбросить пароль</button></form></div></div>)}</div>
  </section>;
}
